sonar.projectKey=prabhuratna
sonar.projectName=Prabhuratna Metals
sonar.sources=backend/src,frontend/src,api
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.sqlite,**/coverage/**,**/.scannerwork/**
sonar.sourceEncoding=UTF-8
